// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3L60_hZpZSSKq1BeSLkHcvre3EzmlZS0',
    appId: '1:168682792411:web:c1e90a52ae8520628a33fe',
    messagingSenderId: '168682792411',
    projectId: 'buoyant-idea-397819',
    authDomain: 'buoyant-idea-397819.firebaseapp.com',
    storageBucket: 'buoyant-idea-397819.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyNXQPH47O1rNiR3GWPdcFnPC1fPv0kcE',
    appId: '1:168682792411:android:96b8668c57d306918a33fe',
    messagingSenderId: '168682792411',
    projectId: 'buoyant-idea-397819',
    storageBucket: 'buoyant-idea-397819.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmDVryVMogw6eFC43Z56m-6Is9_CjenZI',
    appId: '1:168682792411:ios:e78f1447fc3c25448a33fe',
    messagingSenderId: '168682792411',
    projectId: 'buoyant-idea-397819',
    storageBucket: 'buoyant-idea-397819.appspot.com',
    iosBundleId: 'com.example.animalTrivia',
  );
}
